hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: ../models/
  - _self_

data:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv

haar:
  frontalface: ../models/haarcascade/haarcascade_frontalface_alt.xml